### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by ZhangLe1993** [fudan-generative-vision/hallo2#11]
```
(hallo) root@ecm-e6d2:/home/code/hallo2# python scripts/inference_long.py --config ./configs/inference/long.yaml
Traceback (most recent call last):
  File "/home/code/hallo2/scripts/inference_long.py", line 36, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/anaconda3/envs/hallo/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by julius-richter** [comment]
Had the same error. Worked for me after: 

`pip install huggingface_hub==0.25.00`

**Comment by ZhangLe1993** [comment]
> pip install huggingface_hub==0.25.00

Okay, this issue has been solved, but other issues have arisen

**Comment by ZhangLe1993** [comment]
> Had the same error. Worked for me after:
> 
> `pip install huggingface_hub==0.25.00`

onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/2d106det.onnx failed:Protobuf parsing failed.

**Comment by julius-richter** [comment]
I didn't get this error. Could you try:

```python
import onnx
model = onnx.load("path/to/2d106det.onnx")
onnx.checker.check_model(model)
```

Or try:

`pip install onnxruntime --upgrade`

**Comment by ZhangLe1993** [comment]
> failed

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729427742.503101 1263526 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729427742.583903 1263648 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 535.154.05), renderer: NVIDIA A10/PCIe/SSE2
Traceback (most recent call last):
  File "/home/code/hallo2/scripts/inference_long.py", line 508, in <module>
    save_path = inference_process(command_line_args)
  File "/home/code/hallo2/scripts/inference_long.py", line 216, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "/home/code/hallo2/hallo/datasets/image_processor.py", line 141, in preprocess
    get_mask(source_image_path, cache_dir, face_region_ratio)
  File "/home/code/hallo2/hallo/utils/util.py", line 554, in get_mask
    landmarks, height, width = get_landmark(file)
  File "/home/code/hallo2/hallo/utils/util.py", line 418, in get_landmark
    with FaceLandmarker.create_from_options(options) as landmarker:
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/mediapipe/tasks/python/vision/face_landmarker.py", line 3104, in create_from_options
    return cls(
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Unable to read the file in zip archive.
```

**Comment by cuijh26** [comment]
Maybe you could try to download this file manually from https://huggingface.co/fudan-generative-ai/hallo2/blob/main/face_analysis/models/2d106det.onnx. 

And use the code to check.
> ```python
> import onnx
> model = onnx.load("path/to/2d106det.onnx")
> onnx.checker.check_model(model)
> ```

**Comment by ZhangLe1993** [comment]
> Maybe you could try to download this file manually from https://huggingface.co/fudan-generative-ai/hallo2/blob/main/face_analysis/models/2d106det.onnx.
> 
> And use the code to check.
> 
> > ```python
> > import onnx
> > model = onnx.load("path/to/2d106det.onnx")
> > onnx.checker.check_model(model)
> > ```

Thanks, I found out that it was the model I downloaded the problem, I was in Chinese mainland, so I used the proxy image and hfd tool to download, and the problem was solved one by one after re-downloading the model

**Comment by cuijh26** [comment]
ok

**Comment by AricGamma** [comment]
Closing this issue. If any other questions, please open a new one.
