### ISSUE TITLE
python scripts/inference_long.py --config ./configs/inference/long.yaml

### ISSUE THREAD

**Issue by clocad** [fudan-generative-vision/hallo2#14]
Traceback (most recent call last):
  File "D:\hallo2\scripts\inference_long.py", line 36, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "D:\hallo2\hallo\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "D:\hallo2\hallo\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "D:\hallo2\hallo\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (D:\hallo2\hallo\lib\site-packages\huggingface_hub\__init__.py)
![cmd_3taUvAb6Rc](https://github.com/user-attachments/assets/dd421123-da6d-42c0-9821-ed79f98eef8f)

**Comment by cuijh26** [comment]
you can pip list, check if huggingface_hub exitsts or not. If don't exist, you could try to 'pip install huggingface_hub==0.25.2'

**Comment by julius-richter** [comment]
Had the same error. Worked for me after:

`pip install huggingface_hub==0.25.00`

**Comment by clocad** [comment]
yes it worked, thank you

**Comment by AricGamma** [comment]
#11
