### ISSUE TITLE
[ERROR] failed (exitcode: -11)

### ISSUE THREAD

**Issue by Jaylen-Lee** [fudan-generative-vision/hallo2#56]
8卡3090，128g内存；这里的错误是因为驱动还是硬件？如何排查？
```Could not find checkpoint under ./exp_output/stage1/checkpoints, start training from scratch
Steps:   0%|                                                                                                | 0/30000 [00:00<?, ?it/s][2024-11-26 02:04:28,494] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 750661 closing signal SIGTERM
[2024-11-26 02:04:28,495] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 750664 closing signal SIGTERM
[2024-11-26 02:04:28,495] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 750668 closing signal SIGTERM
[2024-11-26 02:04:31,514] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 1 (pid: 750662) of binary: /home/jinlin_li/anaconda3/envs/hallo/bin/python
Traceback (most recent call last):
  File "/home/jinlin_li/anaconda3/envs/hallo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1042, in launch_command
    deepspeed_launcher(args)
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 754, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jinlin_li/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
scripts.train_stage1 FAILED
--------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-26_02:04:28
  host      : ruc-NF5468M5
  rank      : 2 (local_rank: 2)
  exitcode  : -11 (pid: 750663)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 750663
[2]:
  time      : 2024-11-26_02:04:28
  host      : ruc-NF5468M5
  rank      : 4 (local_rank: 4)
  exitcode  : -11 (pid: 750665)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 750665
[3]:
  time      : 2024-11-26_02:04:28
  host      : ruc-NF5468M5
  rank      : 5 (local_rank: 5)
  exitcode  : -11 (pid: 750666)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 750666
[4]:
  time      : 2024-11-26_02:04:28
  host      : ruc-NF5468M5
  rank      : 6 (local_rank: 6)
  exitcode  : -11 (pid: 750667)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 750667
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-26_02:04:28
  host      : ruc-NF5468M5
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 750662)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 750662
========================================================```

**Comment by Jaylen-Lee** [comment]
使用了错误版本的cuda，已解决
