### ISSUE TITLE
InvalidProtobuf: [ONNXRuntimeError] : 7

### ISSUE THREAD

**Issue by ZhangLe1993** [fudan-generative-vision/hallo2#7]
`Traceback (most recent call last):
  File "/home/code/hallo2/scripts/inference_long.py", line 35, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
(base) root@ecm-e6d2:/home/code/hallo2# conda activate hallo
(hallo) root@ecm-e6d2:/home/code/hallo2# python scripts/inference_long.py --config ./configs/inference/long.yaml
save path:  ./output_long/debug/1
Traceback (most recent call last):
  File "/home/code/hallo2/scripts/inference_long.py", line 508, in <module>
    save_path = inference_process(command_line_args)
  File "/home/code/hallo2/scripts/inference_long.py", line 210, in inference_process
    with ImageProcessor(img_size, face_analysis_model_path) as image_processor:
  File "/home/code/hallo2/hallo/datasets/image_processor.py", line 100, in __init__
    self.face_analysis = FaceAnalysis(
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/1k3d68.onnx failed:Protobuf parsing failed.`

**Comment by AricGamma** [comment]
Maybe it is caused by incomplete onnx file. Try to compare the sha256 checksum with the hash on huggingface.
![image](https://github.com/user-attachments/assets/8185e07b-5f50-41af-8447-bda1f01ca82e)

**Comment by ZhangLe1993** [comment]
<img width="878" alt="image" src="https://github.com/user-attachments/assets/afe601c3-4915-4c49-8284-5d9f6dff0050">

I've confirmed that the file is OK, but I'm still getting this error

**Comment by ZhangLe1993** [comment]
The error has changed again, does this look like the CPU is used to execute it?

`(hallo) root@ecm-e6d2:/home/code/hallo2# python scripts/inference_long.py --config ./configs/inference/long.yaml
save path:  ./output_long/debug/1
2024-10-18 11:22:59.830222243 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./pretrained_models/face_analysis/models/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Traceback (most recent call last):
  File "/home/code/hallo2/scripts/inference_long.py", line 508, in <module>
    save_path = inference_process(command_line_args)
  File "/home/code/hallo2/scripts/inference_long.py", line 210, in inference_process
    with ImageProcessor(img_size, face_analysis_model_path) as image_processor:
  File "/home/code/hallo2/hallo/datasets/image_processor.py", line 100, in __init__
    self.face_analysis = FaceAnalysis(
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/2d106det.onnx failed:Protobuf parsing failed.`

**Comment by ZhangLe1993** [comment]
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/608caecd-92f3-4b8b-903c-ed80f40ccc0d">

**Comment by cuijh26** [comment]
Could you show me your cuda version?

**Comment by ZhangLe1993** [comment]
Yes, This My cuda Version

```
(hallo) root@ecm-e6d2:/home/code/hallo2# nvidia-smi
Fri Oct 18 11:47:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                     Off | 00000000:00:08.0 Off |                    0 |
|  0%   41C    P0              57W / 150W |   3216MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2101      C   python3                                    3208MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by k18coldwl** [comment]
@ZhangLe1993 check those libraries in your Python environment. Make sure those libraries are available.
1. cuda
2. pytorch
3. onnxrumtime-gpu

**Comment by k18coldwl** [comment]
> <img alt="image" width="1268" src="https://private-user-images.githubusercontent.com/26535477/377709092-608caecd-92f3-4b8b-903c-ed80f40ccc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjM0MzQsIm5iZiI6MTcyOTIyMzEzNCwicGF0aCI6Ii8yNjUzNTQ3Ny8zNzc3MDkwOTItNjA4Y2FlY2QtOTJmMy00YjhiLTkwM2MtZWQ4MGY0MGNjYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmYyMzAyMjgwZTNkMjVjOWY1NjQzY2RjNzE0M2IxNmM3YjczMDM2MTM0MmU2MWVlZjY1MmE4NjFmYmFlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ck-GzqSDKSeQMtzLjAkOzsdSrQusi4RKO2GBV6h-epg">

you can try to uninstall the onnxruntime  and  onnxruntime-gpu libs first, and reinstall onnxruntime-gpu, please makesure the version is match for the pytorch's version.

**Comment by ZhangLe1993** [comment]
<img width="606" alt="image" src="https://github.com/user-attachments/assets/0634f904-1010-43f9-8bea-6c719d5b6ebd">


> @ZhangLe1993 check those libraries in your Python environment. Make sure those libraries are available.
> 
> 1. cuda
> 2. pytorch
> 3. onnxrumtime-gpu

**Comment by ZhangLe1993** [comment]
> > <img alt="image" width="1268" src="https://private-user-images.githubusercontent.com/26535477/377709092-608caecd-92f3-4b8b-903c-ed80f40ccc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjM0MzQsIm5iZiI6MTcyOTIyMzEzNCwicGF0aCI6Ii8yNjUzNTQ3Ny8zNzc3MDkwOTItNjA4Y2FlY2QtOTJmMy00YjhiLTkwM2MtZWQ4MGY0MGNjYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmYyMzAyMjgwZTNkMjVjOWY1NjQzY2RjNzE0M2IxNmM3YjczMDM2MTM0MmU2MWVlZjY1MmE4NjFmYmFlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ck-GzqSDKSeQMtzLjAkOzsdSrQusi4RKO2GBV6h-epg">
> 
> you can try to uninstall the onnxruntime and onnxruntime-gpu libs first, and reinstall onnxruntime-gpu, please makesure the version is match for the pytorch's version.

This image can not reached

**Comment by ZhangLe1993** [comment]
<img width="739" alt="image" src="https://github.com/user-attachments/assets/1f8a02e9-7769-467e-bb5d-a53364e3f79d">

**Comment by cuijh26** [comment]
Maybe you could reinstall the python environment according to README. I try to reinstall it, and find it work well.

**Comment by ZhangLe1993** [comment]
Can I use the following command to speed up？

```
pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages
pip install -r requirements.txt  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages

```

**Comment by cuijh26** [comment]
> Can I use the following command to speed up？
> 
> ```
> pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages
> pip install -r requirements.txt  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages
> ```

In theory, yes. I am trying to use this command to install this environment again. Maybe you can run this command without speeding up.

**Comment by ZhangLe1993** [comment]
> > Can I use the following command to speed up？
> > ```
> > pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages
> > pip install -r requirements.txt  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --break-system-packages
> > ```
> 
> In theory, yes. I am trying to use this command to install this environment again. Maybe you can run this command without speeding up.

If I don't use the acceleration command, the installation of dependencies will be very slow, and I completely configure the environment according to the README, only the acceleration command is different from the README

**Comment by AricGamma** [comment]
Hi, let me know that is your problem solved and what's the latest update. I'll help to deal with it.

**Comment by cckamiya** [comment]
同样的问题 ，该如何解决

**Comment by cuijh26** [comment]
可以尝试手动下载模型。可以参考这个：https://github.com/fudan-generative-vision/hallo2/issues/11#issuecomment-2424947373
